public let layoutMap = [
  "us": "ABC",
  "ara-mac": "Arabic",
  "ara-mac-phonetic": "Arabic-QWERTY",
  "ara-digits": "ArabicPC",
  "br": "Brazilian-ABNT2",
  "ca": "CanadianFrench-PC",
  "us-colemak": "Colemak",
  "us-dvorak": "Dvorak",
  "us-dvorak-l": "Dvorak-Left",
  "us-dvorak-r": "Dvorak-Right",
  "bt": "Dzongkha",
  "hu-102_qwertz_dot_nodead": "Hungarian",
  "hu-qwerty": "Hungarian-QWERTY",
  "is": "Icelandic",
  "la-stea": "Lao",
  "latam": "LatinAmerican",
  "lt": "Lithuanian",
  "lt-std": "Lithuanian-LST1582",
  "ru-phonetic_mac": "Russian-Phonetic",
  "ru": "RussianWin",
  "th": "Thai",
  "tr-f": "Turkish-Standard",
  "ua-macOS": "Ukrainian",
  "uz": "Uzbek-Cyrillic",
]
